const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.TextBox.Exps.Text
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{play: 0},
	{Toque: 0},
	{Sprite2: 0},
	{Sólido: 0},
	{Chão: 0},
	{Projétil: 0},
	{picareta: 0},
	{ouro: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{player: 0},
	{direita: 0},
	{esquerda: 0},
	{Sprite3: 0},
	{particula_ouro: 0},
	{particula_morte: 0},
	{Sprite4: 0},
	{Texto: 0},
	{Áudio: 0},
	{record_points: 0},
	{Sprite5: 0},
	{AJAX: 0},
	{Botão: 0},
	{Sprite6: 0},
	{NomeJogador: 0},
	{Voltar: 0},
	{pontos: 0},
	{Record: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Chão: class extends self.ITiledBackgroundInstance {},
	picareta: class extends self.ISpriteInstance {},
	ouro: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	direita: class extends self.ISpriteInstance {},
	esquerda: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	particula_ouro: class extends self.IParticlesInstance {},
	particula_morte: class extends self.IParticlesInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	record_points: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Botão: class extends self.IButtonInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	NomeJogador: class extends self.ITextInputInstance {},
	Voltar: class extends self.IButtonInstance {}
}